# Generated by Django 3.0.2 on 2020-02-13 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_auto_20200213_1629"),
        ("api", "0003_auto_20200213_1552"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="facility",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.Facility",
            ),
            preserve_default=False,
        )
    ]
