# Generated by Django 3.0.2 on 2020-02-13 16:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("api", "0004_patient_facility")]

    operations = [
        migrations.RemoveField(model_name="videoupload", name="dob"),
        migrations.RemoveField(model_name="videoupload", name="name"),
        migrations.AddField(
            model_name="videoupload",
            name="date_recorded",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="videoupload",
            name="patient",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.Patient"
            ),
            preserve_default=False,
        ),
    ]
