# Generated by Django 3.0.2 on 2020-03-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0008_auto_20200302_0739")]

    operations = [migrations.RemoveField(model_name="patient", name="uid")]
