# Generated by Django 3.0.2 on 2020-03-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0009_remove_patient_uid")]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=50,
                verbose_name="Gender",
            ),
        )
    ]
