# Generated by Django 3.0.2 on 2020-03-11 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0010_auto_20200309_1041")]

    operations = [
        migrations.RemoveField(model_name="videoupload", name="dob"),
        migrations.RemoveField(model_name="videoupload", name="name"),
        migrations.AddField(
            model_name="videoupload",
            name="comment",
            field=models.TextField(default="", verbose_name="Comment"),
        ),
        migrations.AddField(
            model_name="videoupload",
            name="patient",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="api.Patient"
            ),
            preserve_default=False,
        ),
    ]
