# Generated by Django 3.0.2 on 2020-03-12 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0011_auto_20200311_1636"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Diagnosis Comment")),
                ("date_added", models.DateField(auto_now_add=True)),
                (
                    "physician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "videoupload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.VideoUpload",
                    ),
                ),
            ],
        )
    ]
