# Generated by Django 3.0.2 on 2020-03-15 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0012_diagnosis")]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="videoupload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnosis",
                to="api.VideoUpload",
            ),
        )
    ]
