# Generated by Django 3.0.2 on 2020-03-21 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0013_auto_20200315_1625"),
    ]

    operations = [
        migrations.RenameModel(old_name="Diagnosis", new_name="DoctorComment"),
        migrations.AddField(
            model_name="videoupload",
            name="doctor_status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("reopened", "Reopened"),
                    ("archived", "Archived"),
                ],
                default="new",
                max_length=50,
                verbose_name="Doctor's Status",
            ),
        ),
        migrations.AddField(
            model_name="videoupload",
            name="screener_status",
            field=models.CharField(
                choices=[
                    ("pending_initial_review", "Pending Initial Review"),
                    ("reviewed", "Reviewed"),
                    ("archived", "Archived"),
                ],
                default="pending_initial_review",
                max_length=50,
                verbose_name="Screener's Status",
            ),
        ),
        migrations.AddField(
            model_name="videoupload",
            name="under_review_by_doctor",
            field=models.BooleanField(
                default=False, verbose_name="Under Review by Doctor"
            ),
        ),
    ]
