# Generated by Django 3.0.2 on 2020-03-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0015_screenercomment")]

    operations = [
        migrations.AlterField(
            model_name="doctorcomment",
            name="videoupload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.VideoUpload"
            ),
        )
    ]
