# Generated by Django 3.0.2 on 2020-03-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0016_auto_20200327_1032")]

    operations = [
        migrations.AlterField(
            model_name="doctorcomment",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="screenercomment",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
