# Generated by Django 3.0.2 on 2020-03-27 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0017_auto_20200327_1035")]

    operations = [
        migrations.AlterField(
            model_name="doctorcomment",
            name="videoupload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_comments",
                to="api.VideoUpload",
            ),
        ),
        migrations.AlterField(
            model_name="screenercomment",
            name="videoupload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screener_comments",
                to="api.VideoUpload",
            ),
        ),
    ]
