# Generated by Django 3.0.2 on 2020-04-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0018_auto_20200327_1038")]

    operations = [
        migrations.AlterModelOptions(
            name="doctorcomment", options={"ordering": ["-date_added", "-id"]}
        ),
        migrations.AlterField(
            model_name="videoupload",
            name="screener_status",
            field=models.CharField(
                choices=[
                    ("pending_review", "Pending Review"),
                    ("reviewed", "Reviewed"),
                    ("archived", "Archived"),
                ],
                default="pending_review",
                max_length=50,
                verbose_name="Screener's Status",
            ),
        ),
    ]
