# Generated by Django 3.0.2 on 2020-02-13 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("accounts", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facility_name",
                    models.CharField(
                        blank=True,
                        max_length=225,
                        null=True,
                        verbose_name="Facility Name",
                    ),
                ),
                (
                    "facility_country",
                    models.CharField(
                        blank=True,
                        max_length=225,
                        null=True,
                        verbose_name="Facility Country",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="UserProfile"),
    ]
