# Generated by Django 3.0.2 on 2020-02-13 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("accounts", "0002_auto_20200213_1610")]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        )
    ]
