# Generated by Django 3.0.2 on 2020-02-13 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("accounts", "0004_auto_20200213_1620")]

    operations = [
        migrations.AlterModelOptions(
            name="facility", options={"verbose_name_plural": "Facilities"}
        ),
        migrations.AlterField(
            model_name="facility",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
